version: '3.7'

services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        image: php-apache-cli
        container_name: php-aws
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        depends_on:
            - mysql
    mysql:
        image: 'mysql:latest'
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge